### ISSUE TITLE
Script does not let me select extrusion selection or distance

### ISSUE THREAD

**Issue by Loewkie** [pointwise/ScaledOffset#1]
Whenever I run the script on a closed set of connectors it immediately extrudes the connectors inwards. There is no option for me to control either the direction or the magnitude of the extrusion.

**Comment by dbgarlisch** [comment]
Did you read this script's instructions?
https://github.com/pointwise/ScaledOffset#operation

**Comment by Loewkie** [comment]
Yes I did, I did not realize that you had to specify the offset in the code itself. Might be good to have that as an option in the GUI when running the script. Is easier to vary the settings that way :)

**Comment by dbgarlisch** [comment]
Feel free to add a Tcl/Tk GUI to this script and submit a pull request when you are done!
For an example, see the [RotateView](https://github.com/pointwise/RotateView) script.
Thanks!
